name: Testing simdjson PHP extension
on: [push, pull_request]

jobs:
  Tests:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: "Tests on PHP ${{ matrix.php-version }} (${{ matrix.os }})"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: json
          tools: pecl, phpize, php-config

      - name: "Build extension"
        env:
          NO_INTERACTION: true
        run: |
          php-config --extension-dir
          phpize
          ./configure
          sudo make
          sudo make install
          sudo make test

      - name: "Show"
        run: "php -dextension=simdjson.so --ri simdjson"

      - name: "Error diff"
        if: ${{ failure() }}
        run: |
          for i in tests/*.diff tests/*/*.diff; do
          	echo "=========================================================================="
          	echo $i
          	echo "--------------------------------------------------------------------------"
          	cat $i
          	echo "=========================================================================="
          	echo
          done
